### ISSUE TITLE
Self-signed certificate - disabling warning

### ISSUE THREAD

**Issue by obrigg** [cisco-en-programmability/dnacentersdk#1]
Thanks for creating this SDK!
Trying it out with the DevNet sandbox DNAC - it works fine.
However, when I tried pulling my lab's DNAC, I got the following error:
> requests.exceptions.SSLError: HTTPSConnectionPool(host='X.X.X.X', port=443): Max retries exceeded with url: /dna/system/api/v1/auth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))

Adding "requests.packages.urllib3.disable_warnings() " to the script did not help.

How can I use the SDK with self-signed certificates?

Regards,
Oren.

**Comment by zapodeanu** [comment]
Hi, 
Thank you for the interest in the SDK.
the config.py file includes the option to configure the SDK to use your lab Cisco DNA Center:

# Package Constants
DEFAULT_BASE_URL = 'https://sandboxdnac2.cisco.com:443'

DEFAULT_SINGLE_REQUEST_TIMEOUT = 60

DEFAULT_WAIT_ON_RATE_LIMIT = True

**DEFAULT_VERIFY = True**, change to False

DEBUG_ENVIRONMENT_VARIABLE = 'DEBUG'
