### ISSUE TITLE
Poor naming of function: v2_3_5_3/authentication_management.py : authentication_ap_i(

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacentersdk#102]
**Prerequisites**
* [ ] Have you tested the operation in the API directly? Yes
* [ ] Do you have the latest SDK version? Yes
* [ ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
The name of the function is confusing since network as ap mostly stands for access points. 
v2_3_5_3/authentication_management.py Function name: authentication_ap_i

**Expected behavior**
The name to be modified to either: authentication or authentication_api

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.5.3
* Python version:
* SDK version: dnacentersdk-2.6.3
* OS Version:

**Comment by fmunozmiranda** [comment]
Hi @DNACENSolutions in new SDK version, name was updated, please verify it and feel free to close this issue.
