### ISSUE TITLE
function name changed in 2.3.3.0 from update_ssid_to_ip_pool_mapping to update_ssid_to_ip_pool_mapping2

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacentersdk#104]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [ ] Do you have the latest SDK version?
* [ ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
The update_ssid_to_ip_pool_mapping function which also existing from 2.2.3.3 (update_ssid_to_ip_pool_mapping) got changed to update_ssid_to_ip_pool_mapping3 in 2.3.3.0. and again 2.3.5.0 it is again : update_ssid_to_ip_pool_mapping. 
Can you fix it in 2.3.3.0??
https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/v2_3_3_0/fabric_wireless.py
  def update_ssid_to_ip_pool_mapping2(self,
                                        scalableGroupName=None,
                                        siteNameHierarchy=None,
                                        ssidNames=None,
                                        vlanName=None,
                                        headers=None,
                                        payload=None,
                                        active_validation=True,
                                        **request_parameters):

**Expected behavior**
the function name changed should be restored to update_ssid_to_ip_pool_mapping.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Python version:
* SDK version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @fmunozmiranda please verify it in new SDK version, and let us know how does it goes.
