### ISSUE TITLE
Function names changed in v2.3.5.0 libs all function got added with 2 though no change in DNAC APIs

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacentersdk#106]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [ Yes] Do you have the latest SDK version?
* [ ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
All the function names for module: dnacentersdk/api/v2_3_5_3/licenses.py
are changed and got added 2 in it. 
  def device_count_details2(self,
 def device_license_summary2(self,
 def device_license_details2(self,
etc.
**Expected behavior**
Function names should be restored as in 2.3.3.0 version so there is no break for any user or ansible users. 

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Python version:
* SDK version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @DNACENSolutions please verify it in new SDK version, and let us know how does it goes.
