### ISSUE TITLE
Function name changed to assign_device_credential_to_site in DNAC2.3.5.0(dnacentersdk/api/v2_3_5_3/network_settings.py) 

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacentersdk#107]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [Yes ] Do you have the latest SDK version?
* [ ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.
https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/v2_3_5_3/network_settings.py
Older versions function names:
https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/v2_3_3_0/network_settings.py
https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/v2_2_3_3/network_settings.py

**Describe the bug**
The function name of the SDK function changed to assign_device_credential_to_site from assign_credential_to_site. The function names should not change every release as the function used by customer will have break in their APPs. 

**Expected behavior**
The function name should be restored to  assign_credential_to_site

**Screenshots**

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.5.3
* Python version:
* SDK version:2.6.3
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @DNACENSolutions please verify it in new SDK version, and let us know how does it goes.
