### ISSUE TITLE
Module name is changed dnacentersdk/api/v2_3_3_0/platform_configuration.py to v2_3_5_3/platform.py

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacentersdk#108]
**Prerequisites**
* [Yes ] Have you tested the operation in the API directly?
* [yes ] Do you have the latest SDK version?
* [ ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
The whole module is change from 2.3.3.0 to 2.3.5.3 though there is no change in controller APIs. This will need changes in app for those who is already using this. 
**Expected behavior**
Maintain the same module and function names across version to keep the customer APP working.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Python version:
* SDK version:2.6.3
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @DNACENSolutions please verify it in new SDK version, and let us know how does it goes.
Feel free to close the issue.
