### ISSUE TITLE
API Urls have changed

### ISSUE THREAD

**Issue by halkan1** [cisco-en-programmability/dnacentersdk#11]
We are using DNA Center 1.3.3.3 and the api urls seems to have changed thus breaking this SDK. I noticed it when playing around with getting our templates. 
The hardcoded URL in the SDK is:
/dna/intent/api/v1/template-programmer/template

but in the new version of DNA Center it is:
api/v1/template-programmer/template

**Comment by zapodeanu** [comment]
@Halkan1 I checked with my cluster running 1.3.3.3 and the API has not changed. The SDK does not support version 1.3.3.3, I working on having it updated. Due to this it is not tested for version 1.3.3.3.

**Comment by halkan1** [comment]
@zapodeanu 
It appears that you are correct as an old Cisco blog I found states the API uses the URL {hostname}/api/v1/... but non the less the hardcoded URL in template_programmer.py (the e_url variable) is still set to '/dna/intent/api/v1/' which doesn't work. 

I will be honest and say I have not deciphered all of the SDK code but I did notice that if I changed all occurrences of '/dna/intent/' to '/' instead the SDK started working for me.

**Comment by halkan1** [comment]
Hi again,

An update on this. It turns out that this is a bug in DNAC. CSCvr70208 as found here:
https://www.cisco.com/c/en/us/td/docs/cloud-systems-management/network-automation-and-management/dna-center-platform/1-3-3-0/release_notes/b_dnac_platform_rn_1_3_3_0.html#id_130777

So after I applied the workaround it started working as expected without altering the hardcoded URL in the SDK.

Sorry for stirring things up.
