### ISSUE TITLE
user_and_roles::Unable to use user and roles module.

### ISSUE THREAD

**Issue by JayaVamsiKrishnaSaiVolla** [cisco-en-programmability/dnacentersdk#112]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
Unable to use user_and _roles module, getting attribute error with 2.3.5.3

error log : 

'DNACenterAPI' object has no attribute 'user_and_roles'
Traceback (most recent call last):
  File "/ws/sjc-it/jvolla/dnac-auto/tools/SolDubugger/solservices/dnac_module/users/dnac_users.py", line 71, in configure_user_SDK
    response = self.dsdk.user_and_roles.add_user_ap_i(
AttributeError: 'DNACenterAPI' object has no attribute 'user_and_roles'

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  2.3.7.0-70290
* Python version: 3.7
* SDK version: 2.6.4

**Comment by fmunozmiranda** [comment]
@JayaVamsiKrishnaSaiVolla  thanks for report, verify again please with new version.
