### ISSUE TITLE
Users and Roles:: Delete user API 

### ISSUE THREAD

**Issue by JayaVamsiKrishnaSaiVolla** [cisco-en-programmability/dnacentersdk#115]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
There was no method to delete the User and delete the role in user_and _roles could you please bring these two methods as well.

DELETE USER API : "/dna/system/api/v1/user/${userId}"
DELETE ROLE API : "/dna/system/api/v1/role/${roleId}"

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  2.3.7
* Python version: 3.8
* SDK version: 2.6.4
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Hi @JayaVamsiKrishnaSaiVolla, By documentation it can be seen that these methods are not supported or at least included in version 2.3.5.3 of the Cisco DNA Center API:

![image](https://github.com/cisco-en-programmability/dnacentersdk/assets/93611708/8b0fd1e2-9ded-4d0b-bc25-5763497dbeed)

**Comment by fmunozmiranda** [comment]
Hey actually I'm going to close this issue.

But you can use this apis with this:
https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/custom_caller.py

Hope this help you.
