### ISSUE TITLE
Make MyDict cachable

### ISSUE THREAD

**Issue by steffenschumacher** [cisco-en-programmability/dnacentersdk#12]
Hi,
I'm using flask_caching to cache certain responses from DNA Center, where the responses are MyDicts
flask_cache uses Pickle for object serialisation, and would support MyDicts also with a slight modification - namely adding these overrides:

    def __getstate__(self):
        return self.__dict__

    def __setstate__(self, d):
        self.__dict__.update(d)

I can find no harm in doing this, and it allows me to cache the responses, so I think this should be considered into the build?

**Comment by zapodeanu** [comment]
Thank you for your recommendations. We will take this in consideration as we are in the process to update the Cisco DNA Center SDK for the latest Cisco DNA Center version.
