### ISSUE TITLE
2.3.3.0 API add_vn method does not seem to be passing the site and vn to the API correctly/at all

### ISSUE THREAD

**Issue by paulbauer1** [cisco-en-programmability/dnacentersdk#122]
**Prerequisites**
* [ Yes] Have you tested the operation in the API directly?
* [ Yes] Do you have the latest SDK version?
* [ Yes] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
When using the sdk with the 2.3.3.0 API version through Ansible or directly in python the add_vn method fails. I don't know if the API for this call has changed significantly, but the code in the method is different between 2.3.3.0 and 2.3.5.3. The 2.3.3.0 version has no parameters for the site and vn. The 2.3.5.3 API works as expected. Based on the compatibility matrix and my version of DNAC and Ansible I believe the recommended SDK version is 2.5.5 which has the same error but there is no option to move to the 2.3.5.3 API as 2.3.3.0 is the highest option in 2.5.5.

**Expected behavior**
Virtual networks should be added to fabric site. 

**Screenshots**
![failed_api_call](https://github.com/cisco-en-programmability/dnacentersdk/assets/10010378/270cc35d-b563-4588-8619-63b03abf287b)
![successfull_api_call_dnac_explorer](https://github.com/cisco-en-programmability/dnacentersdk/assets/10010378/5ef1a9c2-ce35-4eff-b631-e464e5ec1277)
![successfull_api_call_sdk](https://github.com/cisco-en-programmability/dnacentersdk/assets/10010378/b232e706-3a26-42d0-8a29-00cec712221b)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.3.7-72323
* Python version:python:3.9.17
* SDK version:2.6.7
* OS Version: 5.15.49-linuxkit-pr aarch64 GNU/Linux

**Additional context**

**Comment by DbarrantesE** [comment]
Hi @paulbauer1, try using the latest version of dnacentersdk (2.6.8). In this version, according to the comments on the issue, it was fixed. Try testing again to see if there's anything else we need to adjust in the code.

**Comment by fmunozmiranda** [comment]
Closed due inactivity.
