### ISSUE TITLE
AP port assignment API not working with DNAC APIs of 2.3.3.0

### ISSUE THREAD

**Issue by ragadegithub** [cisco-en-programmability/dnacentersdk#126]
**Prerequisites**
* [ .] Have you tested the operation in the API directly?
* [ .] Do you have the latest SDK version?
* [. ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

Yes all Prereqs met
**Describe the bug**
API for AP port assignment  fails with below error even when the payload has all the right information.
The exact same payload works with Requests / Postman API call.

ERROR :: - {'siteNameHierarchy': 'Real/stie/hierarcy', 'deviceManagementIpAddress': '10.10.10.140', 'interfaceName': 'GigabitEthernet3/0/7', 'dataIpAddressPoolName': 'POOLNAME', 'authenticateTemplateName': 'Closed Authentication', 'interfaceDescription': 'ACCESS-POINT'} is invalid. Reason: data.authenticateTemplateName must be one of ['No Authentication', 'Open Authentication', 'Closed Authentication ', 'Low Impact']

**Expected behavior**
The payload is correct and the API must have executed.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.3.7
* Python version: 3.10
* SDK version: 2.6.7
* OS Version: Windows

**Additional context**

checking through the payload validation section of SDK code, there seems to be an extra space in the below file:
This could be potential cause.
code works as expected if validation is set to "False"
file :
dnacentersdk/models/validators/v2_3_3_0/jsd_e4a09bf566f35babad9e27f5eb61a86d.py

line 47:

                "enum": [
                "No Authentication",
                "Open Authentication",
                "Closed Authentication ",    <<<< extra space.
                "Low Impact"
                ],

**Comment by zapodeanu** [comment]
@ragadegithub The extra space comes from the API documentation. The SDK validates against the allowed values for the Auth Template Name

**Comment by ragadegithub** [comment]
@zapodeanu , the API call using POSTMAN works without that Extra space. 
In this case, i believe there has to be a documentation bug for the API :) 

at this point, the only way i could get the script working is by setting the "active_validation" to false.

is it possible to update the SDK before the API documentation process?

**Comment by zapodeanu** [comment]
@ragadegithub Maybe the API works with both the extra space and without the extra space. However, the libraries are developed using the API documentation, which includes the extra space.
@fmunozmiranda  Could this fix be added to one library releases with bug fixes? Thank you

**Comment by fmunozmiranda** [comment]
Fixed in v2.6.9. Closing the issue, if there is other problem related to this, please re-open it.
