### ISSUE TITLE
Configuration template export template - request validator error

### ISSUE THREAD

**Issue by HongPhatTL** [cisco-en-programmability/dnacentersdk#135]
**Prerequisites**

- [x] Have you tested the operation in the API directly?
- [x] Do you have the latest SDK version?
- [x] Review the compatibility matrix before opening an issue.

**Prerequisites**
I was running the Ansible module ```cisco.dnac.configuration_template_export_template```, (which indirectly using the dnacentersdk), the validator : ``validators/v2_3_5_3/jsd_dc254215fdf25cd5b7ba797e8f8faebf.py`` raised a exception that list of ids is invalid, it must be object (further details in screeshots).
But when I disabled the request validator, the codes work just fine.

**Expected behavior**
According to DNACenter's developer toolkit, the request body for ``/dna/intent/api/v1/template-programmer/template/exporttemplates`` (POST) has to be a list of template IDs (further details in screeshots).

**Screenshots**
Result of using API directly on DNAC developer toolkit, errors in code terminal and the Ansible playbook code.

![issue_3](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/5f971cfe-d3c8-420b-88b7-61d40d7d14f0)

![issue_2](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/f002c7a1-1be6-4553-bac4-6ab3d5af0fcf)

![issue_1](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/c15965a3-7b71-40d8-b131-b157366ff7f1)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  2.3.5.3 
* Python version: 3.8
* SDK version:  2.6.9

**Comment by fmunozmiranda** [comment]
This issue will be addressed here: https://github.com/cisco-en-programmability/dnacentersdk/issues/138
