### ISSUE TITLE
Mismatch in parameters from expected payload in the backend and payload sent by SDK for claiming a WLC

### ISSUE THREAD

**Issue by abimishr** [cisco-en-programmability/dnacentersdk#136]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
I am trying to claim a WLC using the API “claim a device to a site” (/onboarding/pnp-device/site-claim). Catalyst WLC requires additional parameters like Static IP, subnet mask, Vlan ID etc. Since, DNAC's developer tool kit has an issue with the documentation, the SDK is also following the same documentation. Current documentation and SDK code takes vlanID and InterfaceName. However, the API expects it to be vlanId and ipInterfaceName respectively in the backend. I have raised a documentaion bug previously with the API team and it's in progress. Hence, requesting here to make the same change in SDK's code under device_onboarding_pnp.py file in claim_a_device_to_a_site method.

**Expected behavior**
Device gets claimed after calling the API, generates Day 0 config and gets provisioned on the DNAC GUI.

**Screenshots**
<img width="1725" alt="Screenshot 2023-11-14 at 10 25 16 PM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/135167972/ebec97fb-1cbe-486d-932d-b6d5d0c46d10">

<img width="1104" alt="Screenshot 2023-11-14 at 10 28 47 PM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/135167972/7623765e-9fa9-4da1-bc84-e80ee9734803">

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: Version 2.3.7.0-70333
* Python version: 3.8.10
* SDK version: 2.6.5
* OS Version: Ubuntu 20.04.6 LTS

**Additional context**
Link to the bug raised for the API team: https://cdetsng.cisco.com/webui/#view=CSCwh91999

**Comment by bvargasre** [comment]
Hi @abimishr version 2.6.10 is available try this new version
Most of the mentioned parameters were already there
interfaceName to ipInterfaceName was corrected
Test it and let us know it works for you

**Comment by abimishr** [comment]
Hi @bvargasre thanks for the update. I suppose 2.6.10 got available recently. Thanks for the super quick resolution.
