### ISSUE TITLE
Configuration template export project - request validator error

### ISSUE THREAD

**Issue by MUTHU-RAKESH-27** [cisco-en-programmability/dnacentersdk#138]
**Prerequisites**
* [yes] Have you tested the operation in the API directly?
* [yes] Do you have the latest SDK version?
* [yes] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
I was running the Ansible module for the cisco.dnac.configuration_template_export_project, which in turn calls the SDK, raises an exception that the list of project names is invalid. It says that it must be an object. Refer screenshots.

**Expected behavior**
According to the DNA Cente's developer toolkit, the request body for the dna/intent/api/v1/template-programmer/project/name/exportprojects (POST) has to be a list of project names. Refer screenshots.

**Screenshots**
Result of using API directly on DNAC developer toolkit, errors in code terminal and the Ansible playbook code.
<img width="455" alt="Screenshot 2023-11-29 at 5 05 32 PM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/114211490/85a1d0cc-9441-440a-994b-f351f525e8d1">
<img width="1512" alt="Screenshot 2023-11-29 at 5 10 01 PM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/114211490/7d9ed36a-8611-4d09-b888-f89a47962428">
<img width="1497" alt="Screenshot 2023-11-29 at 5 11 30 PM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/114211490/db53d6c6-db04-4301-b53f-932474c3889a">

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.7.3
* Python version: 3.8
* SDK version: 2.6.10

**Comment by HongPhatTL** [comment]
I suggest a quick get-around is to set ```validate_response_schema``` value to ```false```

![image](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/d9f6e787-51ad-4eb1-a3f7-a635f4b3e6aa)

**Comment by MUTHU-RAKESH-27** [comment]
@HongPhatTL Still throwing the same error. Is this working fine for your issue?

**Comment by HongPhatTL** [comment]
Yes, @MUTHU-RAKESH-27. Absolutely !

### When I set ```validate_response_schema: true```, I get the same error as you had.
![validate_true](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/885ba627-a67f-4bed-8405-4ac7ef7cd029)

 ### When ```validate_response_schema: false```, the error goes away.
![validate_false](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/9654cb08-7600-42f0-be86-cd2eaf3ea16e)

I argue that there are issues with the request validator in DNACSDK : ```python3.8/site-packages/dnacentersdk/models/validators/v2_3_5_3/jsd_dc254215fdf25cd5b7ba797e8f8faebf.py``` (in term of my issue)

![image](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/33257bf6-05a0-4e92-8312-1bc0d17a91e8)

**Comment by HongPhatTL** [comment]
Hi @MUTHU-RAKESH-27,  regarding your issue, please check file ```python3.8/site-packages/dnacentersdk/models/validators/v2_3_5_3/jsd_e6ea8c5d425cf9ac77006f5593725f.py```

![image](https://github.com/cisco-en-programmability/dnacentersdk/assets/110651444/bb151f66-6011-48de-872f-e6849bf3d529)

**Comment by fmunozmiranda** [comment]
Hi, @MUTHU-RAKESH-27 , temporaly please use parameter active_validation in SDK or validate_response_schema in ansible with False value. Actually we don´t have sufficient documentation for this endpoint. So it´s better if you just skip the validation.

If you´re using parameters and still getting troubles, please pass us DEBUG of your playbooks to help you.

Regards.

**Comment by bvargasre** [comment]
Since there is no documentation of the request body it was decided to remove the validation for this method.
I will close the issue, in case the problem persists or another one arises feel free to reopen it or open a new issue.
