### ISSUE TITLE
Configuration template import project - check_type error

### ISSUE THREAD

**Issue by MUTHU-RAKESH-27** [cisco-en-programmability/dnacentersdk#139]
**Prerequisites**
* [yes] Have you tested the operation in the API directly?
* [yes] Do you have the latest SDK version?
* [yes] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
I was running the Ansible module for the cisco.dnac.configuration_template_import_project, which in turn calls the SDK, raises an exception that the sdk check_type expects a dict or list but while calling the API it throws an error( expecting string instead of dict or list). Refer screenshots.

**Expected behavior**
According to DNACenter's developer toolkit, the request body for /dna/intent/api/v1/template-programmer/project/importprojects (POST) has to be a string but the SDK expects a dict. (further details in screeshots).

**Screenshots**
<img width="512" alt="Screenshot 2023-11-30 at 12 50 11 AM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/114211490/6dd046bc-8ca7-4c9e-a2bd-9a3ee1bc343e">
<img width="1268" alt="Screenshot 2023-11-30 at 12 51 08 AM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/114211490/04b157ef-0283-4744-a006-576be804415c">

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.7.3
* Python version: 3.8
* SDK version: 2.6.10

**Comment by fmunozmiranda** [comment]
Hi, @MUTHU-RAKESH-27 , temporaly please use parameter `active_validation` with `False` value. Actually we don´t have sufficient documentation for this endpoint. So it´s better if you just skip the validation.

Regards.
