### ISSUE TITLE
GET for /dna/intent/api/v1/network-device breaks with empty JSON payload

### ISSUE THREAD

**Issue by NathanDotTo** [cisco-en-programmability/dnacentersdk#14]
There is a defect in the DNAC SDK devices.py code, line 547:

    if with_custom_headers:
        json_data = self._session.get(endpoint_full_url, params=params,
                                      json=_payload, headers=_headers)
    else:
        json_data = self._session.get(endpoint_full_url, params=params,
                                      json=_payload)
Passing in json=_payload for a get request is generally unusual, and for this specific API, e_url = ('/dna/intent/api/v1/network-device') definitely not supported. In 2.1.1.1 it breaks.

**Comment by jbogarin** [comment]
Nathan,

Thanks for the report. We are actually on the process of upgrading the SDK from the official 1.2.10 support to get up to 2.1.1. We'll definitively take a look at this during the process, which should have an update in the next two or three weeks.

**Comment by jbogarin** [comment]
Nathan,

We already check and it's definitively a bug in the code. We'll fix this with the new release of the SDK which should come in about two weeks.
