### ISSUE TITLE
TypeError: got multiple values for argument 'headers' in device_license_details method

### ISSUE THREAD

**Issue by ngtanthanh-qc** [cisco-en-programmability/dnacentersdk#144]
https://github.com/cisco-en-programmability/dnacentersdk/blob/9e71edbc2406a2c9ab610c3201fd7b32877106d9/dnacentersdk/api/v2_3_5_3/licenses.py#L357

https://github.com/cisco-en-programmability/dnacentersdk/blob/9e71edbc2406a2c9ab610c3201fd7b32877106d9/dnacentersdk/api/v2_3_3_0/fabric_wireless.py#L245

These codes will raise TypeError: <2nd_func> got multiple values for argument 'headers' OR 'scalableGroupName'

I believe the issue lies in the redundant passing of self as an argument to `device_license_details2` and `update_ssid_to_ip_pool_mapping2`

**Comment by bvargasre** [comment]
Hi @ngtanthanh-qc, the problem should have been fixed with the new version of dnacentersdk 2.7.1.
I will close the issue, in case the problem persists or another one arises feel free to reopen it or open a new issue.
