### ISSUE TITLE
Upgrade to Python 3.12 break the SDK

### ISSUE THREAD

**Issue by FlavienJP** [cisco-en-programmability/dnacentersdk#145]
**Prerequisites**
* [x] Have you tested the operation in the API directly? Not Related
* [x] Do you have the latest SDK version? Yes
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
I've upgraded my interpreter to Py 3.12 (dependency need it) and it breaks the code.

ModuleNotFoundError: No module named 'imp'

You can find a thread about it => https://discuss.python.org/t/how-do-i-migrate-from-imp/27885/26

**Expected behavior**
Fresh install of venv with a fresh install of packages.

**Screenshots**

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  Not Needed
* Python version: 3.12
* SDK version: 2.6.11
* OS Version: Last MacOS.

**Additional context**
I also need to install "setuptool" to fix ModuleNotFoundError: No module named 'pkg_resources' error.

**Comment by bvargasre** [comment]
Hi @FlavienJP, the problem should have been fixed with the new version of dnacentersdk 2.7.1
Try it and if it works feel free to close the issue.

**Comment by bvargasre** [comment]
I'm going to close this issue.
Any problems that arise feel free to open a new issue or reopen this one
Best regards.
