### ISSUE TITLE
EASY FIX - Change check_type(offset, basestring) to allow integers 

### ISSUE THREAD

**Issue by NetworkingB2A** [cisco-en-programmability/dnacentersdk#147]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest SDK version?
* [X] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
The module > dnacentersdk/dnacentersdk/api/v2_3_5_3/tag.py > get_tag_members_by_id()  only allows basestring type and not integers. This causes script to fail if int is provided. 

**Expected behavior**
I believe the offset and the limit should be changed to allow an int value.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  Version 2.3.5.5-70026
* Python version: 3.11
* SDK version: 2.3.5.3
* OS Version: Red Hat Enterprise Linux 8.9 (Ootpa)

**Additional context**
Here is where code is
[Code to fix](https://github.com/cisco-en-programmability/dnacentersdk/blob/9e71edbc2406a2c9ab610c3201fd7b32877106d9/dnacentersdk/api/v2_3_5_3/tag.py#L737)

**Comment by bvargasre** [comment]
I'm going to close this issue, in the new version offset and limit accept int and str.
Any problems that arise feel free to open a new issue or reopen this one.
Best regards.
