### ISSUE TITLE
Update readthedocs-sphinx-search

### ISSUE THREAD

**Issue by stsewd** [cisco-en-programmability/dnacentersdk#15]
Looks like you are using an old version of the extension

https://github.com/cisco-en-programmability/dnacentersdk/blob/b752b32091deb010a6c61306bf3b059ce83d7e70/Pipfile.lock#L381-L384

We updated the endpoint used by the search extension, so old versions will stop working soon. Please use the new version of the extension https://github.com/readthedocs/readthedocs-sphinx-search (we have releases in pypi now ;))

**Comment by wastorga** [comment]
@stsewd Done, thanks for the heads up.
