### ISSUE TITLE
 Issue in adding/updating headers while configuring Webhook Destination and ambiguity in Args description for headers in Create/Update Webhook Destination API

### ISSUE THREAD

**Issue by Abhishek-121** [cisco-en-programmability/dnacentersdk#150]
**Prerequisites**
* [ yes] Have you tested the operation in the API directly?
* [yes ] Do you have the latest SDK version?
* [ yes] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
While working on adding headers during the creation/updation of Webhook Destination, I observed that in the DNAC --> Platform --> Developer Toolkit.

API's - Create Rest Webhook Destination/ Update Rest Webhook Destination are accepting headers as a list of dictionary in the payload and able to create/update with mentioned payload.

Dnacentersdk version - 2.9.0,
API Used -  '/dna/intent/api/v1/event/webhook'

But when I try same by giving the input payload in the playbook as list of dictionary using the below playbook

<img width="643" alt="image" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/43b3c37d-823e-49f6-a6eb-335341730f72">

I got this error - 
 
**"msg": "Error while Adding the Webhook destination with the name 'webhook Iac2' in Cisco Catalyst Center: We were expecting to receive an instance of one of the following types: 'dict'or 'None'; but instead we received [{'name': 'X-Auth-Token', 'value': 'qejfkq;ejwf;kqjrfkjewqkfjdekwlqjfdklqwe;j', 'defaultValue': None, 'encrypt': None}] which is a 'list'.",**
 
And also when I try to change by passing headers as a dictionary instead of list of dictionary using the below input in playbook -

<img width="603" alt="image" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/dd8904ac-c6a7-4ebe-aba7-8b8b45686753">

I got this error - 
 
**"errors": ["Create WebhookConfig failed due to Parsing WebhookConfig failed Cannot deserialize instance of `java.util.ArrayList<com.cisco.dna.event.common.models.flow.Parameter>` out of START_OBJECT token\n at [Source: (String)\"{\"name\": \"webhook Iac2\", \"description\": \"webhhok description for iac2.0\", \"url\": \[https://10.195.227.14/dna\](https://10.195.227.14/dna/), \"method\": \"POST\", \"trustCert\": false, \"headers\": {\"name\": \"X-Auth-Token\", \"value\": \"qejfkq;ejwf;kqjrfkjewqkfjdekwlqjfdklqwe;j\", \"default_value\": null, \"encrypt\": null}, \"isProxyRoute\": true}\"; line: 1, column: 160] (through reference chain: com.cisco.dna.event.common.models.event.artifact.WebhookConfig[\"headers\"])"]**

<img width="1792" alt="Console_error" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/36cd171c-1a9c-4888-a260-cd93d35975c5">

Upon looking more into the **Dnacentersdk version - 2.9.0**, I got to know that there is ambiguity in both Create/Update Webhook Destination  as there in arguments it's mentioned that headers can be list of dictionaries or it can be dictionary only.

<img width="1273" alt="sdk_create_webhook" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/c6c3743b-4cfb-4868-9858-8933a865d432">

<img width="1146" alt="sdk_update_webhook" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/b80016c2-916c-4254-b324-61f96649b2e2">

**Also in the Args description of both SDK API we are supporting both types that is headers as dict and headers as list.**

**Expected behavior**

As per the Cisco Catalyst GUI we can add only one type of header and if we are try to add other it will give the error -

        **Headers must have a single form of authentication**

![image](https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/ced93bf4-2371-432f-9983-6f9b4f48bda0)

**Screenshots**
<img width="749" alt="create_webhook" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/9ae0e46d-a96d-4686-8ce3-3a284cdac40d">

<img width="797" alt="update_webhook" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/393afaf7-b5d8-4287-b07b-d9474e4f7747">

<img width="1619" alt="image" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/1c132085-f222-4a01-a539-f8b54af2ef27">

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  2.3.7.0-70333
* Python version: 3.9
* SDK version: 2.9.0

**Comment by bvargasre** [comment]
Hello @Abhishek-121, it was a bug, currently our sdk supports custom headers for the request, what happens is that here there is a headers field, causing this error because both had the same name.
Upload a new version 2.9.1, try with that and tell me if it worked or not.

**Comment by Abhishek-121** [comment]
Hi @bvargasre , with the new sdk version 2.9.1. I am able to execute the playbook with headers but the problem is headers are still not reflected in the DNAC GUI as a result the problem still exists to add/update headers while configuring webhook destination.
<img width="1591" alt="webhook_added" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/0d625708-951b-49e0-88f4-1745a39b6495">

<img width="594" alt="no_headers" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/56202291/66e1da08-516f-4842-9f7e-7671e142ee41">

![Uploading Screenshot 2024-05-08 at 2.17.26 PM.png…]()

**Comment by bvargasre** [comment]
Hi @Abhishek-121,  could you activate the debug in ansible with dnac_debug: True or export DNAC_DEBUG=True and send me the whole output
Also to clarify headers is a list

**Comment by Abhishek-121** [comment]
[logs_output.log](https://github.com/cisco-en-programmability/dnacentersdk/files/15271742/logs_output.log)

Also, from user we taking input as headers only but in our module code before invoking 'add_webhook_destination' API in the payload we convert headers --> customHeaders.

You can check the payload by filtering the given string - " Payload for creating webhook destination"

**Comment by bvargasre** [comment]
Hi @Abhishek-121 , in the log you sent me I don't see debug enabled.
What I need is that you activate the debug to be able to observe the api calls.
The debug in ansible can be activated in two ways:
- 1 Exporting it as an environment variable for example.
`export DNAC_DEBUG=True`
- 2 Defining it in playbook for example:
``` yaml
 tasks:
- name: Test
  cisco.dnac.event_webhook_create:
    dnac_debug: True
    description: "webhok description for iac2.0"
    headers:
    - defaultValue: string
      encrypt: False
      name: "X-Auth-Token"
      value: "qejfkq;..."
    method: "Put"
    name: "TestwebHoodIac23"
    trustCert: False
    url: "url"
```
With this you should notice that in the logs will appear the calls to the Catalys lab api.

-------
Finally if you can pass me the output of those logs together with the playbook used for the test, so I can check the behavior and detect if the problem is the playbook or ansible or sdk.
The same would be for issue #151.
I remain available for any further assistance.

**Comment by Abhishek-121** [comment]
Hi @bvargasre , I apply the same still not getting logs. Although upon investigation in the SDK 2.9.1 with version 2.3.7.5 in event_management.py module I came across that still in payload we are taking headers only and you mentioned to use customeHeaders.

 _payload = {
            'webhookId':
                webhookId,
            'name':
                name,
            'description':
                description,
            'url':
                url,
            'method':
                method,
            'trustCert':
                trustCert,
            'headers':   <----------- it should be customeHeaders I believe
                headers,
            'isProxyRoute':
                isProxyRoute,
        }

Also, not able to get the logs having the calls to the Catalys lab api.

**Comment by Abhishek-121** [comment]
Hi @bvargasre,  

I’ve noticed that the issue described here has resurfaced in the latest version of the SDK (2.9.4). The functionality for handling headers in webhook destination creation/updating is broken again.  

Could you please reopen this issue for further investigation? I am happy to provide additional details or test fixes if needed.  

Thank you for your support!  

Regards,  
Abhishek
