### ISSUE TITLE
SDK for the Cisco ISE server retry functionality (FAILED to INPROGRESS) is not supported

### ISSUE THREAD

**Issue by MUTHU-RAKESH-27** [cisco-en-programmability/dnacentersdk#157]
**Prerequisites**
* [yes] Have you tested the operation in the API directly?
* [yes] Do you have the latest SDK version?
* [yes] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
Unable to get the ISE server back to INPROGRESS state from FAILED state using accept_cisco_ise_server_certificate_for_cisco_ise_server_integration under the system_settings.py SDK when the certificate is not trusted.

In the GUI, under Platform -> Developer Toolkit -> System Settings -> Accept Cisco ISE Server Certificate for Cisco ISE Server Integration, it is clearly mentioned that for retrying we have to pass {} to the API. Even in the SDK it is clearly mentioned.

<img width="1340" alt="Screenshot 2024-06-22 at 1 13 39 PM" src="https://github.com/cisco-en-programmability/dnacentersdk/assets/114211490/1b120f2a-7a23-46d9-9484-0b76a1c0f995">

I am getting this error for "Expecting value: line 1 column 1 (char 0)" for the payload 
                "id": cisco_ise_id,
                "isCertAcceptedByUser": trusted_server,
                "payload": {},

and The error was: [406] Not Acceptable - NCND00067: The request body is invalid
                "id": cisco_ise_id,
                "payload": {},

The retry functionality is important for our ansible module development!

**Expected behavior**
The SDK should support for the retry functionality for the Cisco ISE server.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Python version: 3.9
* SDK version: 2.9.1

**Comment by bvargasre** [comment]
Hi @MUTHU-RAKESH-27 
I'm going to close this issue, in the new version the problem should be solved.
Any problems that arise feel free to open a new issue or reopen this one.
Best regards.
