### ISSUE TITLE
Verify set to False is not being honored

### ISSUE THREAD

**Issue by ignaciofite** [cisco-en-programmability/dnacentersdk#159]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest SDK version?
* [X] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
When one sets the environmental variable `DNA_CENTER_VERIFY=False` the SDK ignores it. This is an issue because sometimes SSL verification will fail since the cert is not signed and therefore the SDK won't work.

**Expected behavior**
When setting `DNA_CENTER_VERIFY=False` SSL verification should be skipped.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: N/A
* Python version: N/A
* SDK version: 2.7.1
* OS Version: N/A

**Additional context**
I believe the problem is this part of the code within `_init.py_`:
```
        if verify is None:
            verify = dnacenter_environment.get_env_verify() or DEFAULT_VERIFY
```

Since `DEFAULT_VERIFY` is always True, it doesn't matter what `dnacenter_environment.get_env_verify()` returns...

**Comment by bvargasre** [comment]
I'm going to close this issue, in the new version the problem of exporting verify was fixed.
Any problems that arise feel free to open a new issue or reopen this one.
Best regards.
