### ISSUE TITLE
SDK for the API 'update_network_v2' is not returning the entire exception message

### ISSUE THREAD

**Issue by MUTHU-RAKESH-27** [cisco-en-programmability/dnacentersdk#164]
**Prerequisites**
* [yes] Have you tested the operation in the API directly?
* [yes] Do you have the latest SDK version?
* [yes] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
The SDK for the API 'update_network_v2' under the family 'network_settings' is not returning the entire exception msg. It is returning only the message which is under the key 'message'. That information is not sufficient and clear. 

**Expected behavior**
It is expected to get the entire exception message as the image.

**Screenshots**
![156aed94-61d6-4bcc-a31b-5600ad27eb24](https://github.com/user-attachments/assets/f174eb8b-7c15-467b-9116-d4424944a2fb)
![0eb74cf4-c399-4edb-95f7-da8f26ae5c12](https://github.com/user-attachments/assets/bc275b20-18ab-47c9-859c-c19b82a48390)

**Environment (please complete the following information):**
* Python version: 3.9
* SDK version: 2.9.1

**Comment by bvargasre** [comment]
Hi @MUTHU-RAKESH-27 
I'm going to close this issue, in the new version when an error comes with the details field, it will be added to the final SDK response.
Any problems that arise feel free to open a new issue or reopen this one.
Best regards.
