### ISSUE TITLE
Clarification on SDK API Response with 400 status code not able to get exact failure reason as API returning generic exception message of Bad Request.

### ISSUE THREAD

**Issue by Abhishek-121** [cisco-en-programmability/dnacentersdk#172]
**Prerequisites**
* [ yes ] Have you tested the operation in the API directly?
* [ yes ] Do you have the latest SDK version?
* [ yes ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
I am currently working on the SDA module development using Ansible and dnacentersdk version 2.9.2. I’ve encountered an issue where a single API returns a 400 response status code with a generic exception message in case of failure, even though the failure reason varies in different cases. This makes it difficult to identify the exact cause of the failure as the SDK API provides a general exception message, which looks like:
 
Exception:
An error occurred when executing operation. The error was: [400] Bad Request - Bad Request
 
Here are a few examples from the 'Add_layer3_virtual_networks' API where the 400 status code is returned with different failure reasons, but the SDK still outputs the same generic exception message. This poses a challenge in development, as we're unable to provide the specific failure reason to users:
 
Response Status Code 400 - Creating L3 VN with Pending Operation:
 
{
    "response": {
        "errorCode": "NCSP11353",
        "message": "Bad Request",
        "detail": "NCSP11353: Not able to proceed with the operation because of pending operations on the same intent. Further operations are not permitted until the existing ones are deployed or discarded. Additional info for support: Pending operation(s): [Deploying Layer 3 Virtual Networks (0191bb73-6427-7302-a453-6191e93d67b1)]."
    },
    "version": "1.0"
}
 
Response Status Code 400 - Creating L3 VN with the Same Name:
 
{
    "response": {
        "errorCode": "NCHS20460",
        "message": "Bad Request",
        "detail": "Layer 3 Virtual Network Creation failed in SDA Fabric. The given virtualNetworkName 'VN_anchor' already exists, please use another name."
    },
    "version": "1.0"
}
 
Response Status Code 400 - Creating L3 VN with Anchor Site and Multiple Fabric Site IDs:
 
{
    "response": {
        "errorCode": "NCHS20464",
        "message": "Bad Request",
        "detail": "Layer 3 Virtual Network Creation/Update failed for VN_anchor1 in SDA Fabric. Each VN can only be anchored to one site. Please ensure there is only one fabric ID in the fabricIds field in the create request. You can add this virtual network to other sites after anchoring is done. Currently, the VN is assigned to all provided fabrics but not anchored."
    },
    "version": "1.0"
}
 
 
Would it be possible to have a mechanism in place to fetch the detailed failure messages from the API response in cases where a 400 status code is returned? This would allow us to provide more precise feedback to the users regarding the exact failure reason, rather than a generic message.

**Expected behavior**
Here is the expected behaviour if somehow API gets failed while executing and give 400 as status code along with the details of the failure reason then we should be able to get the failure Reason as it will help the user to get the exact failure reason instead of generic message - 
**An error occurred when executing operation. The error was: [400] Bad Request - Bad Request**

**Screenshots**
<img width="1792" alt="Generic Exception msg" src="https://github.com/user-attachments/assets/e484c6b4-fd5b-4578-bfda-af53d5b10e67">

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.7.6-75360
* Python version: 3.9.0
* SDK version: 2.9.2

**Comment by fmunozmiranda** [comment]
You can enable DEBUG to see whole API call. Does that work for you?
