### ISSUE TITLE
Support for Event Management (webhook) - DNA Center 1.3.1

### ISSUE THREAD

**Issue by robertcsapo** [cisco-en-programmability/dnacentersdk#2]
- Delete Event Subscriptions
- Count of Event Subscriptions
- Get Events
- Count of Events
- Count of Notifications
- Get Status API for Events
- Get Event Subscriptions
- Get Notifications
- Create Event Subscriptions
- Update Event Subscriptions

![image](https://user-images.githubusercontent.com/11992244/66610709-59af4000-eb71-11e9-9baf-125533db8a80.png)

**Comment by zapodeanu** [comment]
The SDK does not have support for 1.3.1.x at this time. We will support the Event Management APIs when we have the SDK available for 1.3.1.1
