### ISSUE TITLE
preview_template function overwrites params

### ISSUE THREAD

**Issue by jeremypng** [cisco-en-programmability/dnacentersdk#23]
From api/v2_1_2/configuration_templates.py

`       params = {
        }
        params.update(request_parameters)
        params = dict_from_items_with_values(params)
`

I'm just going to submit a check for None before this entry.

**Comment by wastorga** [comment]
@jeremypng 

Sorry for the delay.

The latest dnacentersdk version fixes that issue (really since version 2.2.2). The internal variable `params` was replaced with `_params`.
