### ISSUE TITLE
Add support for business-api

### ISSUE THREAD

**Issue by jeremypng** [cisco-en-programmability/dnacentersdk#27]
The sites.create_site endpoint returns an executionId that links to:

{'executionId': '9ea46ac1-d8ed-4da6-9dab-b88adf488c4e',
 'executionStatusUrl': '/dna/platform/management/business-api/v1/execution-status/9ea46ac1-d8ed-4da6-9dab-b88adf488c4e',
 'message': 'The request has been accepted for execution'}

Are there plans to include this api endpoint in a separate module or add it to the tasks.py? I can try to submit a PR if someone has some direction here.

**Comment by zapodeanu** [comment]
Hi, The SDK has support for all Cisco DNA Center published APIs. We will include this API when released by Cisco DNA Center. We have this API on the roadmap.

**Comment by wastorga** [comment]
@zapodeanu Just reopen this issue to comment on alternative options.

The dnacentersdk has a way to add API call definitions using `CustomCaller`, you can view [examples in the documentation](https://dnacentersdk.readthedocs.io/en/latest/api/quickstart.html#adding-api-call-definitions).

An check more information on [CustomCaller in the documentation](https://dnacentersdk.readthedocs.io/en/latest/api/api.html#dnacentersdk.api.custom_caller.CustomCaller).

If you need more information to help you regarding this, @jeremypng please open another issue.
