### ISSUE TITLE
retrieves_all_network_devices limits to 500

### ISSUE THREAD

**Issue by jorgebanegas** [cisco-en-programmability/dnacentersdk#28]
how can I query to get all my devices instead of limiting to the first 500. I do not know how much devices I should expect. Is there a function that grabs all of the devices in one response

**Comment by zapodeanu** [comment]
Hi, most of the APIs will have a pagination limit of 500 records, some have a lower limit depending on the amount of data to be returned and the time required to collect the data. If the number of records is lower it will be documented in the API docs. You may receive all records using the offset and limit parameters. For example to get the records 501-600
/dna/intent/api/v1/network-device?offset=' + 501 + '&limit=' + 100
You may get the count of all the network devices with the function devices.get_device_count()
I will ask to have the API docs and the SDK to be updated
