### ISSUE TITLE
Auth URL Auth for 1.2.10

### ISSUE THREAD

**Issue by cunningr** [cisco-en-programmability/dnacentersdk#3]
When installing using pip, I am unable to authenticate against DNA Center 1.2.10 even when setting the version to '1.2.10'

I believe this is due to the 'temp_url' setting in;

https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/authentication.py

which is currently set ```/dna/system/api/v1/auth/token```

On 1.2.10 the working auth path I found is ```/api/system/v1/auth/token```

Maybe the ```authentication_api``` function should also implement version support?

**Comment by jbogarin** [comment]
@cunningr we haven’t seen that problem in our testing. Are you trying with DNA Center sandbox we can test or your own internal one?

If you are doing it with your own server, could you please share a debug. It should be possible defining the environment variable DBEUG

**Comment by zapodeanu** [comment]
Did you do an upgrade to 1.2.10 from a previous image? If yes, please disable the REST API bundle, and re-enable

**Comment by cunningr** [comment]
Hi Gabriel,

Yes I have upgraded from previous version but I can't see a package called
'REST API bundle'.  How/where should disable/enable that?

Thanks,

Rich

**Comment by cunningr** [comment]
Hi Jose,

I am actually struggling to enable the DEBUG (this my own DNAC appliance).
The docs say that it should be a ENV variable of type Boolean.  If export
it like so;

# export DEBUG=true

I don't get any additional debug output;

cisco@cisco:~/EMEAR-Enterprise-Networking/python/tables$ python3 apiDb.py
Traceback (most recent call last):
  File "apiDb.py", line 15, in <module>
    api = DNACenterAPI(base_url="https://3.6.12.241:443", version='1.2.10',
verify=False)
  File
"/home/cisco/.local/lib/python3.6/site-packages/dnacentersdk/api/__init__.py",
line 259, in __init__
    access_token=get_access_token(),
  File
"/home/cisco/.local/lib/python3.6/site-packages/dnacentersdk/api/__init__.py",
line 251, in get_access_token
    encoded_auth=encoded_auth).Token
  File
"/home/cisco/.local/lib/python3.6/site-packages/dnacentersdk/api/authentication.py",
line 175, in authentication_api
    check_response_code(response, EXPECTED_RESPONSE_CODE['POST'])
  File
"/home/cisco/.local/lib/python3.6/site-packages/dnacentersdk/utils.py",
line 216, in check_response_code
    raise ApiError(response)
dnacentersdk.exceptions.ApiError: [401] Unauthorized - Unauthorized

**Comment by zapodeanu** [comment]
> Hi Gabriel, Yes I have upgraded from previous version but I can't see a package called 'REST API bundle'. How/where should disable/enable that? Thanks, Rich
> […](#)

Please follow the menu:
Platform > Manage > Bundles > DNA Center REST APIs > click to Disable and re-Enable. Reach out to me directly gzapodea@cisco.com if you need help.

**Comment by robertcsapo** [comment]
This issue should be fixed in the latest 1.3.3 and 2.1.x release train of Cisco DNA Center Platform.
_(It's rather an issue on Cisco DNA Center Platform, rather than on the SDK)_

@cunningr @zapodeanu  can't we close this issue? 👍
