### ISSUE TITLE
504 timed out error after setting timed out to 999999

### ISSUE THREAD

**Issue by jorgebanegas** [cisco-en-programmability/dnacentersdk#30]
using the dnac.sites.get_site_health() function and while using it inside a big scaled dnac environment the api call returns with a 504 timed out error after a minute of loading. What is strange is that i declared the single_request_timeout=99999 when declaring the api.DNACenterAPI. Also tried changing the timed out through environmental variables. Any suggestions or tips?

**Comment by zapodeanu** [comment]
Is this an issue with the SDK or API? Did you try to make the API call without the SDK and was it successful?

**Comment by jorgebanegas** [comment]
<img width="611" alt="Screen Shot 2021-02-18 at 2 19 32 PM" src="https://user-images.githubusercontent.com/22305451/108746098-e0b44c80-7509-11eb-8f44-7c648072ac38.png">


Tried using the DNA Center API url /dna/intent/api/v1/site-health and keep receiving this. Any tips on what I should try ?

**Comment by zapodeanu** [comment]
It seems the issue is related to the API and not the SDK. Please open a TAC case to help you with the API call logs.
