### ISSUE TITLE
Secure? Repository Doesn't Match Published Code

### ISSUE THREAD

**Issue by timway** [cisco-en-programmability/dnacentersdk#32]
Is this repository secure or safe? The PyPI package has versions that don't seem to be published here. I can't openly view the code that was released (easily).

https://pypi.org/project/dnacentersdk/

Also, is there a pattern being used here? @jbogarin you mentioned code generation #31 is that true? Is the code for generating in the repo somewhere as well or as that a reference to all of the JS importing and validation from that?

**Comment by jbogarin** [comment]
Tim,

That's an error on my side. I updated the PyPI files but haven't uploaded the code here. I'll do that today.

And no, the code generation tool is not available, and I don't think it will be.

Do you have any other questions?

**Comment by timway** [comment]
Thanks all good. Was just inspecting the code and trying to follow what was happening.

I see bpm_ prefixing a number of the areas and all of the JSON files are prefixed with jsd_. What is the significance or is that just a quirk of the code generation tool?

**Comment by jbogarin** [comment]
Tim,

I just uploaded a new version to PyPI (2.2.2) and created the tag here

The reason was because the Cisco DNA Center lab we used to create this SDK version was missing the `GET /network-device` endpoint documentation and that's what we use to generate the SDK.

I'll send you the bpm_ and jsd_ response tomorrow.

**Comment by wastorga** [comment]
@timway 

Sorry for the delay.

Regarding the bpm_ and jsd_, it is partially a quirk of the code generation tool. Let me explain.

The `jsd_` files under [models/validators/{version}/](https://github.com/cisco-en-programmability/dnacentersdk/tree/master/dnacentersdk/models/validators/v1_2_10) are JSON schema validators. They are mapped in [models/schema_validator.py](https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/models/schema_validator.py).
The dnacentersdk uses the `SchemaValidator`  from `dnacentersdk.models.schema_validator` as a validator, you can see this in [api/__init__.py](https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/__init__.py#L373).

If it is a POST or PUT operation, its SDK function has the `active_validation` parameter, if set to true it calls the appropriate JSON Schema validator. For example, [create_netconf_credentials](https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/v1_2_10/network_discovery.py#L171) mapped to [models/validators/v1_2_10/jsd_17929bc7465bb564.py](https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/models/validators/v1_2_10/jsd_17929bc7465bb564.py)

For the bpm_ files, there is an `object_factory` that uses [dnacentersdk.models.mydict.mydict_data_factory](https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/models/mydict.py) you can see this in [api/__init__.py](https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/api/__init__.py#L372). 

The [mydict_data_factory](https://github.com/cisco-en-programmability/dnacentersdk/blob/master/dnacentersdk/models/mydict.py#L201) does not do any mapping, if it did like the webexteamssdk (which this library is inspired by) it will map the string to the Python object representation of the response body.

Let me know if you have any doubts.
