### ISSUE TITLE
reserve-ip-subpool fails

### ISSUE THREAD

**Issue by maconrad** [cisco-en-programmability/dnacentersdk#35]
Hi All
Reserve IP Subpool fails with dnacentersdk as well as via postman direct to DNAC. 
https://{{dnac}}/dna/intent/api/v1/reserve-ip-subpool/{{siteid}}

Try with following input:
{
    "name": "Test1",
    "type": "Generic",
    "ipv6AddressSpace": false,
    "ipv4GlobalPool": "3.0.0.0/24",
    "ipv4Prefix": true,
    "ipv4PrefixLength": 24,
    "ipv4Subnet": "3.1.0.0"
}

---
Output is Ipv6 Global pool(3.0.0.0/24) is not present even though setting ipv6AddressSpace to false if global pool does not exist.
Another output that can be provoked is "Invalid ip subnet(3.0.0.0/8) address for ipv4 global pool" even if global pool exists.
Input works as excpected through the UI.

**Comment by wastorga** [comment]
The issue is on the Cisco DNA Center API rather than on the SDK.
