### ISSUE TITLE
CustomCaller usage

### ISSUE THREAD

**Issue by cunningr** [cisco-en-programmability/dnacentersdk#4]
Hi,

Are there any examples of how to use the CustomCaller?

https://dnacentersdk.readthedocs.io/en/latest/api/api.html#custom-caller

My assumption is that this can be used to add support for custom or yet 'undocumented' API calls on the fly?

Apologies if this is not the case.

**Comment by jbogarin** [comment]
@cunningr that’s exactly the reason for that custom-caller, being able to use SDK for API calls that are not documented or were not documented when the SDK was released.

I’ll send an example tomorrow or update the README.

**Comment by jbogarin** [comment]
@cunningr sorry for the delay, we updated the documentation. Here is an example of using the custom caller

https://dnacentersdk.readthedocs.io/en/latest/api/quickstart.html#adding-api-call-definitions

Hope it helps.
