### ISSUE TITLE
CDP neighbor

### ISSUE THREAD

**Issue by AstritCepele** [cisco-en-programmability/dnacentersdk#5]
I would like to know if there is a module in the latest SDK for DNAC version 1.3.X to get a CDP neighbor detail. I would like to get the ID and the interface of the neighbor node. Via API n DNAC something like this it is achieved by :  /dna/intent/api/v1/device-enrichment-details.

 

Somehow i can get the data via  dnac.sites.get_physical_topology(). But there is a big amount of data process. The simulated network is about 3000+ devices.

**Comment by zapodeanu** [comment]
Hi, Thank you for your question. Please specify what information is available to use for the query? Device hostname and interface name? 
Are you looking for the device id of the device connected to the device/interface specified?
