### ISSUE TITLE
Command Runner issue: cannot save command output to file

### ISSUE THREAD

**Issue by zhenningx** [cisco-en-programmability/dnacentersdk#50]
From this blog: https://blogs.cisco.com/developer/network-automation-cisco-dna-center-sdk-2

How do you "Retrieve the results and save them to file"? This part is missing from the blog. 

The result from the code given in the blog is a class cmd_output, not a file with the results. 

More discussion here: https://community.cisco.com/t5/cisco-digital-network/dnac-command-runner-question/m-p/4570843

Need to have a way to save the command runner to a file to complete the task.

**Comment by wastorga** [comment]
Hi, @zhenningx.

On the blog post, there seem to be missing code or missing parameters for the actual download of the file.

As stated in the documentation, the function will return a [urllib3.response.HTTPResponse](https://urllib3.readthedocs.io/en/latest/reference/urllib3.response.html#urllib3.response.HTTPResponse.data) class.

The [download_a_file_by_fileid](https://dnacentersdk.readthedocs.io/en/latest/api/api.html#dnacentersdk.api.v2_2_3_3.file.File.download_a_file_by_fileid) function has parameters that handle that response, iterate over its content and write it to file. Those parameters are dirpath and save_file; the file's name is the Content-Disposition header's filename value.

So one quick way to do it is changing this line
```python
cmd_output = dnac.file.download_a_file_by_fileid(task_progress['fileId'])
```
to 
```python
// This saves to the current working directory got by Python: os.getcwd()
cmd_output = dnac.file.download_a_file_by_fileid(task_progress['fileId'], save_file=True).
```
or
```python
// This saves to the directory /tmp
cmd_output = dnac.file.download_a_file_by_fileid(task_progress['fileId'], dirpath='/tmp', save_file=True).
```

I hope that helps.

**Comment by zhenningx** [comment]
That worked. Thanks so much!

**Comment by wastorga** [comment]
For now, it is not possible. However, I am working on a solution. I'll update here when it is done.

**Comment by wastorga** [comment]
@zhenningx

You could also pass the list of device ids directly to the run_read_only_commands_on_devices.

```python

def cmd_runner_v2(devices):
  run_cmd = api.command_runner.run_read_only_commands_on_devices(commands=["show run"], deviceUuids=devices)
  task_info = api.task.get_task_by_id(run_cmd.response.taskId)
  task_progress = task_info.response.progress
  while task_progress == 'CLI Runner request creation':
    task_progress = api.task.get_task_by_id(run_cmd.response.taskId).response.progress
  task_progress = json.loads(task_progress)
  return task_progress

def solution_issue_v2():
  device_list = get_device_list()
  filename = "final_command_output_2.log"
  task_progress = cmd_runner_v2(device_list)
  api.file.download_a_file_by_fileid(task_progress['fileId'], save_file=True,
                                     dirpath='/tmp/devices',
                                     filename=filename)

if __name__ == '__main__':
  solution_issue_v2()

```

_Note: for both solutions you will need the new SDK version_

I hope that helps.

**Comment by zhenningx** [comment]
@wastorga The solution works well! Thanks!

**Comment by wastorga** [comment]
@zhenningx. Your welcome. If there is nothing more, please close the issue.

**Comment by zhenningx** [comment]
Closing the issue. Thanks again.
