### ISSUE TITLE
delete_ip_pool_from_sda_virtual_network

### ISSUE THREAD

**Issue by tali1974** [cisco-en-programmability/dnacentersdk#54]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?

**Describe the bug**
you need to add "siteNameHierarchy" in the parameters

    def delete_ip_pool_from_sda_virtual_network(self,
                                                ip_pool_name,
                                                virtual_network_name,
                                                **siteNameHierarchy**,
                                                headers=None,
                                                **request_parameters):

**Expected behavior**
You need to have 3 parameters and siteNameHierarchy is missing 
'Could not find siteNameHierarchy query parameter. please provide valid siteNameHierarchy and try again.'

**Screenshots**

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Python version:
* SDK version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
Hey @tali1974, we are working on it.

**Comment by fmunozmiranda** [comment]
@tali1974 , a new version of dnacentersdk has been published (v2.4.10), try it again with new version and let us know if works for you.

**Comment by fmunozmiranda** [comment]
Closing this is issue due to inactivity.

**Comment by tali1974** [comment]
Sorry for late reply. Yes it’s working
