### ISSUE TITLE
It is not possible to create a global pool with network_settings.create_global_pool

### ISSUE THREAD

**Issue by nextnoob** [cisco-en-programmability/dnacentersdk#60]
**Prerequisites**
* [X] Have you tested the operation in the API directly?

Yes &rarr; 

Example Payload:

```
{
    "settings": { 
        "ippool": [ 
            { 
                "ipPoolName": "TestPool", 
                "type": "Generic", 
                "ipPoolCidr": "10.253.0.0/20",
                "IpAddressSpace": "IPv4"
            }
        ] 
    }
}
```
* [X] Do you have the latest SDK version?
```
pip show dnacentersdk
Name: dnacentersdk
Version: 2.5.0
Summary: Cisco DNA Center Platform SDK
Home-page: https://dnacentersdk.readthedocs.io/en/latest/
Author: Jose Bogarin Solano
Author-email: jbogarin@altus.cr
License: MIT
Location: c:\users\user1\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
Requires: fastjsonschema, future, requests, requests-toolbelt
Required-by: 
```

**Describe the bug**

Class: classNetworkSettings
Function: create_global_pool(settings=None, headers=None, payload=None, active_validation=True, **request_parameters)

The parameter "IpAddressSpace" in the payload does not allow valid values. This is apparently due to the validator.

Error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dnacentersdk/models/validators/v2_3_3_0/jsd_eecf4323cb285985be72a7e061891059.py", line 97, in validate
    self._validator(request)
  File "<string>", line 37, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data.settings.ippool[0].IpAddressSpace must be one of ['IPv6 or IPv4']
```

When I adjust the validator, the API call works.

```
"IpAddressSpace": {
    "enum": [
        "IPv6",   
        "IPv4"
    ]
```

**Expected behavior**
"IPv4" or "IPv6" should be accepted as value for "IpAddressSpace".

**Screenshots**
![CreateIPPool1](https://user-images.githubusercontent.com/22887888/178482108-8cca64a4-868f-4835-b963-7e115fbd2aba.png)
![CreateIPPool2](https://user-images.githubusercontent.com/22887888/178482127-24d537b6-319d-47a8-ae29-1644f53889f5.png)
![CreateIPPool3](https://user-images.githubusercontent.com/22887888/178482436-dee92660-0c68-4aa1-aa42-58f45263b8b3.png)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: Version 2.2.3.5
* Python version: Python 3.10.5
* SDK version: 2.5.0
* OS Version:  Python:3 Docker Container

**Additional context**

Thanks for maintaining the very good SDK :blush:

**Comment by bvargasre** [comment]
Hi @nextnoob, thanks for report, we will work on it.

**Comment by bvargasre** [comment]
Hi @nextnoob, dnacentersdk has been updated to version 2.5.1, so try this new version and tell me if it works.

**Comment by nextnoob** [comment]
Hi @bvargasre ,

it works perfectly. Thanks for the quick implementation!
