### ISSUE TITLE
Create_Network malformed request for 2.3.3

### ISSUE THREAD

**Issue by pablmartC** [cisco-en-programmability/dnacentersdk#62]
Hi team,

I've DNAC 2.3.3.3 and using the dnacentersdk.
I'm trying to configure the network settings of DNAC by using the create_network function under network_settings class.

I'm passing the following schema

{
  "settings" : {
    "dnsServer": {
      "domainName" : "domain.local",
      "primaryIpAddress": "x.x.x.x"
        }
    }
}

The SDK returns "MalformedRequest", Reason: data.settings.dnsServer.domainName must be one of ['can only contain alphanumeric characters or hypen']

However, when I call the API directly with Python or using the DNAC GUI developer toolkit with exactly the same schema as above, it passes and gets configured.

Regards.

**Comment by bvargasre** [comment]
Hi @pablmartC, thanks for reporting the bug, dnacentersdk has been updated to version 2.5.2, so try this new version and tell me if it works.

**Comment by pablmartC** [comment]
Thank you. It's working now.
