### ISSUE TITLE
DNA Center 2.3.3.4 - Report API Issue

### ISSUE THREAD

**Issue by jumaluwati** [cisco-en-programmability/dnacentersdk#68]
Issue description: 
The **report creation** API doesn't work on DNA Center 2.3.3.4 version (the latest when writing this ). All the parameters are provided and they do work on earlier DNA Center releases (I've tried it on 2.2.3.4) and it works perfectly with dnacentersdk versions 2.2.3.3 & 2.3.3.0

The output when running the code is as follows: 

_**dnacentersdk.exceptions.ApiError: [412] Precondition Failed - report create validation fail message 'category cant be null/empty**_ 

I'm not sure whether there is a new parameter called *category* or its a bug.

Any feedback would be appreciated, 

Thank you

PS the code I'm using along with a mini documentation are available on my account https://github.com/jumaluwati/dnac

**Comment by jumaluwati** [comment]
### Update:
I found a workaround for this issue, simply to the category of the report - i.e. if I'm interested in creating an AP report; that should fall under the AP category.

_How to add the category type:_ 
In the payload parameter add the following 

**payload = {'dataCategory': 'AP'}**

That works for me even with the latest DNAC version as of today 2.3.3.5

**Comment by bvargasre** [comment]
Hi @jumaluwati , if it was a doc error, in the new version of dnacentersdk 2.7.1 it was added.
I will close the issue, in case the problem persists feel free to reopen it.
