### ISSUE TITLE
Constancy in "offset" and "limit" implementation by using datatype to be either "Int" or "string"

### ISSUE THREAD

**Issue by ragadegithub** [cisco-en-programmability/dnacentersdk#78]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?

**Describe the bug**
when using offset and limit for large API outputs, some methods in sdk are using "string" datatype for offset and others are using "int" data type
example: 
api.devices.get_device_list( limit:int, offset: int))
api.tag.get_tag_members_by_id(tag_id, "networkdevice",offset:str ,limit:str  )

**Expected behavior**
Consistency in datatype for "offset" and "limit". 

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: Any
* Python version: 3.9.10
* SDK version: 2.5.4
* OS Version: Windows10 / Ubuntu 20.4

**Additional context**

**Comment by bvargasre** [comment]
Hi @ragadegithub 
dnacentersdk v2.5.6. is available. Offset and limit now support both string and int for Cisco DNA Center version 2.3.3.0.
Feel free to test it and close or comment if necessary.

**Comment by ragadegithub** [comment]
verified the current requirement is available in dnacentersdk==2.5.6
