### ISSUE TITLE
DNACenterAPI.sites.assign_device_to_site() not working?

### ISSUE THREAD

**Issue by daxm** [cisco-en-programmability/dnacentersdk#9]
I can successfully issue a call to DNACenterAPI.sites.assign_device_to_site(device=[list of device objects], site_id="site ID").  I get back the following:
{'executionId': '39ff436e-5733-4f69-9efe-bd327ab72bd3', 'executionStatusUrl': '/dna/platform/management/business-api/v1/execution-status/39ff436e-5733-4f69-9efe-bd327ab72bd3', 'message': 'The request has been accepted for execution'}

And nothing happens.  Not sure what I'm doing wrong here.

**Comment by daxm** [comment]
Making "some" progress.  I've dug into the "execution" message URL and this is the error:
{"site":"Device ip not available in input json {\"device\":[{\"memorySize\":\"NA\",\"family\":\"Switches and Hubs\",\"type\":\"Cisco Catalyst 9300 Switch\",\"roleSource\":\"AUTO\",\"lastUpdateTime\":1581077326254,\"softwareType\":\"IOS-XE\",\"softwareVersion\":\"16.12.1s\",\"apManagerInterfaceIp\":\"\",\"serialNumber\":\"FCW2135G00T\",\"collectionInterval\":\"Global Default\",\"inventoryStatusDetail\":\"<status><general code=\\\"SUCCESS\\\"/></status>\",\"upTime\":\"1 day, 17:41:59.26\",\"hostname\":\"cp-border-1.selfserve.lab\",\"associatedWlcIp\":\"\",\"macAddress\":\"70:1f:53:73:4e:00\",\"reachabilityFailureReason\":\"\",\"reachabilityStatus\":\"Reachable\",\"series\":\"Cisco Catalyst 9300 Series Switches\",\"snmpContact\":\"\",\"snmpLocation\":\"\",\"tagCount\":\"0\",\"tunnelUdpPort\":null,\"waasDeviceMode\":null,\"bootDateTime\":\"2020-02-05 18:27:46\",\"collectionStatus\":\"Managed\",\"errorCode\":null,\"errorDescription\":null,\"interfaceCount\":\"0\",\"lastUpdated\":\"2020-02-07 12:08:46\",\"lineCardCount\":\"0\",\"lineCardId\":\"\",\"locationName\":null,\"managementIpAddress\":\"100.124.0.1\",\"platformId\":\"C9300-48U\",\"location\":null,\"role\":\"ACCESS\",\"deviceSupportLevel\":\"Supported\",\"instanceTenantId\":\"5ddf0d04ef610400c5bd7b87\",\"instanceUuid\":\"94ed59a4-846d-47a2-8e86-94a14ca634cd\",\"id\":\"94ed59a4-846d-47a2-8e86-94a14ca634cd\"}]}","status":"False"}

**Comment by daxm** [comment]
I solved it.  The "devices" variable being passed says it is supposed to be a "device object" but what it really wants is a list of dictionaries like {"ip": "managementIpAddress of device"}.  Just passing the device "object" in isn't good enough as the key name is different than what the assign_device_to_site() expects.

**Comment by zapodeanu** [comment]
Thank you for the update
