### ISSUE TITLE
SDA :: add_default_authentication_profile

### ISSUE THREAD

**Issue by JayaVamsiKrishnaSaiVolla** [cisco-en-programmability/dnacentersdk#97]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
End point URL : "/dna/intent/api/v1/business/sda/authentication-profile"

Schema : siteNameHierarchy(string, required): Path of sda Fabric Site
                 authenticateTemplateName(string, required, enum: No Authentication , Open Authentication, Closed Authentication, Low Impact)

For authenticateTemplateName parameter , input string "No Authentication" [without white space at end] is failing at parameter validation.
Actual API call would still take both strings with and without white spaces.

**Expected behavior**
Api call should still happen as API accepts both strings with and without white.

**Screenshots**
<img width="1097" alt="Screenshot 2023-04-27 at 12 54 35 AM" src="https://user-images.githubusercontent.com/117809185/234681980-7dcd2086-19de-49f4-8375-a7fc415e20a8.png">

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.3.6.0
* Python version:3.6
* SDK version:2.3.3
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
@JayaVamsiKrishnaSaiVolla please try it again with `v2.6.3(latest)` and notify us how does it goes.
