### ISSUE TITLE
SDA:add_multicast_in_sda_fabric: failing at parameter validation for valid payload

### ISSUE THREAD

**Issue by JayaVamsiKrishnaSaiVolla** [cisco-en-programmability/dnacentersdk#99]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
In add_multicast_in_sda_fabric , SDK is failing at payload validation even for valid data.

dnacentersdk.exceptions.MalformedRequest: {'siteNameHierarchy': 'Global/California/San Jose/SJC-23', 'multicastMethod': 'native_multicast', 'multicastType': 'ssm', 'multicastVnInfo': [{'virtualNetworkName': 'VN1', 'ipPoolName': 'mcast_rp_pool_rsv', 'internalRpIpAddress': [], 'externalRpIpAddress': '', 'ssmInfo': [{'ssmGroupRange': '232.0.0.0', 'ssmWildcardMask': '0.255.255.255'}]}]} is invalid. Reason: data.multicastVnInfo[0].ssmInfo must be object

**Expected behavior**
For valid data, payload validation shouldn't fail.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  2.3.6.0
* Python version: 3.6
* SDK version: 2.3.3
* OS Version:

**Comment by fmunozmiranda** [comment]
Hi @JayaVamsiKrishnaSaiVolla please update dnacentersdk to latest version `2.6.2`, try again and notify us how does it goes.
Your Cisco DNA Center Version and patch: 2.3.6.0 is more compability with that version.

**Comment by fmunozmiranda** [comment]
@JayaVamsiKrishnaSaiVolla do you test it with last version?

**Comment by fmunozmiranda** [comment]
Closed due inactivity
